---
variables:
  # External resource names (created by other pipelines)
  resourceGroup: who-sharing
  keyVaultName: ckankv2
  virtualNetworkName: ckanvnet
  subnetName: default
  registry: ckanacr
  logAnalyticsName: ckanla
  appInsightsName: ckanai
  diagnosticSettingName: ckands
  # Target resource names (created by this pipeline)
  postgresHostName: whockandb
  solrAppName: ckansolr
  solr_url: https://ckansolr.azurewebsites.net/solr/
  frontendname: ckansakundu
  publicStorageAccountName: ckanpublicstoragasakundu
  # Derived
  azureResourceManagerConnection: SC-SAKUNDU-RG-WHOSHARING


