---
variables:
  # External resource names (created by other pipelines)
  resourceGroup: SRHD-D-EUW-RG01
  keyVaultName: srhddeuwkv
  virtualNetworkName: srhddeuwvnet
  subnetName: default
  registry: srhddeuwacr
  appInsightsName: srhddeuwai
  logAnalyticsName: srhddeuwlog
  diagnosticSettingName: setByPipeline
  # Target resource names (created by this pipeline)
  postgresHostName: srhddeuwckandb
  solrAppName: srhddeuwckansolr
  frontendname: srhddeuwckan
  # Derived
  azureResourceManagerConnection: SC-${{ variables.resourceGroup }}
