---
variables:
  # Must change
  azureResourceManagerConnection: SC-SAKUNDU-RG-WHOSHARING
  frontendname: ckansakundu
  publicStorageAccountName: ckanpublicstoragasakundu
  registry: ckanacr
  postgresHostName: ckandb
  
  #Should change these
  resourceGroup: ckanrg
  location: westeurope

  #Could change these
  keyVaultName: ckankv
  virtualNetworkName: ckanvnet
  subnetName: default
  logAnalyticsName: ckanla
  diagnosticSettingName: ckands
  appInsightsName: ckanai
  
  solrAppName: ckansolr
  solr_url: https://ckansolr.azurewebsites.net/solr/
