---
variables:
  # External resource names (created by other pipelines)
  resourceGroup: who-sharing
  keyVaultName: ckankv2
  virtualNetworkName: ckanvnet
  registry: ckanacr
  logAnalyticsName: ckanla
  diagnosticSettingName: ckands
  # Target resource names (created by this pipeline)
  postgresHostName: whockandb
  solrAppName: ckansolr
  frontendname: ckan
  publicStorageAccountName: ckanstorage
  # Derived
  azureResourceManagerConnection: SC-SAKUNDU-RG-WHOSHARING


