---
variables:
  # Must change
  azureResourceManagerConnection: SC-SAKUNDU-RG-CKANRG
  frontendname: frontendinckanrg
  publicStorageAccountName: publicstorageinckanrg
  registry: acrinckanrg
  postgresHostName: postgresinckanrg
  solrAppName: solrinckanrg
  solr_url: https://solrinckanrg.azurewebsites.net/solr/
  
  #Should change these
  resourceGroup: ckanrg
  location: westeurope

  #Could change these
  keyVaultName: ckankv
  virtualNetworkName: ckanvnet
  subnetName: default
  logAnalyticsName: ckanla
  diagnosticSettingName: ckands
  appInsightsName: ckanai
  
