---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.2
    hooks:
      - id: markdownlint
        name: Markdown Lint
        args: [-c, './scripts/linting/markdownlint.config']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.21.0
    hooks:
      - id: yamllint
        name: YAML Lint
        args: [-c, './scripts/linting/yamllintconfig.yml', --strict]
  - repo: local
    hooks:
      - id: powershelllint
        name: Powershell Lint
        language: system
        files: \.ps1$
        entry: pwsh
        args: ['./scripts/linting/lint_powershell.ps1']
