---
parameters:
  - name: environment
    type: string

  - name: location
    default: westeurope
    type: string

  - name: resourceGroup
    type: string

  - name: azureResourceManagerConnection
    type: string

  - name: publicStorageAccountName
    type: string

  - name: dependsOn
    type: object
    default: []

jobs:
  - deployment: DeployCKANPublicStorage
    environment: ${{ parameters.environment }}
    dependsOn:
      - ${{ each depends in parameters.dependsOn }}:
          - ${{ depends }}

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: PowerShell@2
              displayName: Setup Agent Tools
              inputs:
                filePath: './scripts/agent/Set-AgentTools.ps1'
                pwsh: true

            - task: AzureCLI@2
              displayName: Set Azure Subscription ID to task variables
              inputs:
                azureSubscription: ${{ parameters.azureResourceManagerConnection }}
                scriptType: 'pscore'
                scriptLocation: 'scriptPath'
                scriptPath: './scripts/environment/New-EnvironmentVariables.ps1'
                addSpnToEnvironment: true

            - task: AzureResourceManagerTemplateDeployment@3
              displayName: Create CKAN Public Storage
              inputs:
                deploymentScope: "Resource Group"
                azureResourceManagerConnection: "${{ parameters.azureResourceManagerConnection }}"
                action: "Create Or Update Resource Group"
                resourceGroupName: "${{ parameters.resourceGroup }}"
                location: ${{ parameters.location }}
                templateLocation: "Linked artifact"
                csmFile: "./arm-templates/data_lake.json"
                csmParametersFile: "./arm-templates/data_lake_parameters.json"
                overrideParameters: >
                  -storageAccountName ${{ parameters.publicStorageAccountName }}
                  -location ${{ parameters.location }}
                deploymentMode: "Incremental"

            - task: AzureCLI@2
              displayName: Set permissions for DDI ADF user in public storage
              inputs:
                azureSubscription: ${{ parameters.azureResourceManagerConnection }}
                scriptType: 'pscore'
                scriptLocation: 'scriptPath'
                scriptPath: './scripts/environment/Set-PublicStorageAccess.ps1'
              env:
                STORAGEACCOUNTNAME: ${{ parameters.publicStorageAccountName }}
                FACTORYNAME: ${{ lower(replace(replace(parameters.resourceGroup, '-RG01', '-DDI'), '-', '')) }}df
                TECHNICALUNIT: DDI
                RESOURCEGROUP: "${{ parameters.resourceGroup }}"
