---
parameters:
  - name: location
    type: string
  - name: resourceGroup
    type: string
  - name: azureResourceManagerConnection
    type: string
  - name: keyVaultName
    type: string
  - name: virtualNetworkName
    type: string
  - name: subnetName
    type: string
  - name: registry
    type: string
  - name: logAnalyticsName
    type: string
  - name: diagnosticSettingName
    type: string

jobs:
- deployment: ProvisionBaseInfra
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: ${{ parameters.azureResourceManagerConnection }}
              scriptType: 'pscore'
              scriptLocation: 'scriptPath'
              scriptPath: './scripts/environment/New-EnvironmentVariables.ps1'
              addSpnToEnvironment: true
            displayName: Set Azure Subscription ID to task variables    
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Create Log Analytics"
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
              action: "Create Or Update Resource Group"
              resourceGroupName: ${{ parameters.resourceGroup }}
              location: ${{ parameters.location }}
              templateLocation: "Linked artifact"
              csmFile: "./arm-templates/log_analytics.json"
              csmParametersFile: "./arm-templates/log_analytics.parameters.json"
              overrideParameters: >
                -logAnalyticsName ${{ parameters.logAnalyticsName }}
                -diagnosticSettingName ${{ parameters.diagnosticSettingName }}
              deploymentMode: "Incremental"
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Create VNET"
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
              action: "Create Or Update Resource Group"
              resourceGroupName: ${{ parameters.resourceGroup }}
              location: ${{ parameters.location }}
              templateLocation: "Linked artifact"
              csmFile: "./arm-templates/vnet.json"
              csmParametersFile: "./arm-templates/vnet.parameters.json"
              overrideParameters: >
                -virtualNetworkName ${{ parameters.virtualNetworkName }}
                -logAnalyticsName ${{ parameters.logAnalyticsName }}
                -diagnosticSettingName ${{ parameters.diagnosticSettingName }}
                -subnetName ${{ parameters.subnetName }}
              deploymentMode: "Incremental"
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Create ACR"
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
              action: "Create Or Update Resource Group"
              resourceGroupName: ${{ parameters.resourceGroup }}
              location: ${{ parameters.location }}
              templateLocation: "Linked artifact"
              csmFile: "./arm-templates/acr.json"
              overrideParameters: >
                -containerRegistryName ${{ parameters.registry }}
                -logAnalyticsName ${{ parameters.logAnalyticsName }}
                -diagnosticSettingName ${{ parameters.diagnosticSettingName }}
              deploymentMode: "Incremental"
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Create KV"
            inputs:
              addSpnToEnvironment: true
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
              action: "Create Or Update Resource Group"
              resourceGroupName: ${{ parameters.resourceGroup }}
              location: ${{ parameters.location }}
              templateLocation: "Linked artifact"
              csmFile: "./arm-templates/keyvault.json"
              csmParametersFile: "./arm-templates/keyvault.parameters.json"
              overrideParameters: >
                -keyVaultName ${{ parameters.keyVaultName }}
                -servicePrincipalId $servicePrincipalId
                -servicePrincipalObjectId $(servicePrincipalObjectId)
                -logAnalyticsName ${{ parameters.logAnalyticsName }}
                -diagnosticSettingName ${{ parameters.diagnosticSettingName }}
              deploymentMode: "Incremental"
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Create App Insights"
            inputs:
              addSpnToEnvironment: true
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
              action: "Create Or Update Resource Group"
              resourceGroupName: ${{ parameters.resourceGroup }}
              location: ${{ parameters.location }}
              templateLocation: "Linked artifact"
              csmFile: "./arm-templates/appinsights.json"
              csmParametersFile: "./arm-templates/appinsights.parameters.json"
              overrideParameters: >
                -name ${{ parameters.appInsightsName }}
                -logAnalyticsName ${{ parameters.logAnalyticsName }}
              deploymentMode: "Incremental"              