---
parameters:

  - name: environment
    type: string

  - name: tag
    type: string

  - name: fromACR
    type: string

  - name: toACR
    type: string

jobs:
  - deployment: PromoteContainerToTestRegistry
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Docker@2
              displayName: Login to Dev ACR
              inputs:
                command: login
                containerRegistry: SC-${{ parameters.fromACR }}
            - script: docker pull "${{ parameters.fromACR }}.azurecr.io/ckan:${{ parameters.tag }}"
              displayName: Pull dev container
            - task: Docker@2
              displayName: Logout of Dev ACR
              inputs:
                command: logout
                containerRegistry: SC-${{ parameters.fromACR }}
            - script: docker tag "${{ parameters.fromACR }}.azurecr.io/ckan:${{ parameters.tag }}" "${{ parameters.toACR }}.azurecr.io/ckan:${{ parameters.tag }}"
            - task: Docker@2
              displayName: Login to Test ACR
              inputs:
                command: login
                containerRegistry: SC-${{ parameters.toACR }}
            - task: Docker@2
              displayName: Push to Test ACR
              inputs:
                command: push
                repository: ckan
                containerRegistry: SC-${{ parameters.toACR }}
                tags: "${{ parameters.tag }}"
