---
trigger:
  - none

stages:
  - stage: Development
    variables:
      - template: ./templates/variables/dev.yml
    jobs:
      - template: ./templates/jobs/ckan-base-infra-job.yml
        parameters:
          location: ${{ variables.location }}
          resourceGroup: ${{ variables.resourceGroup }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          keyVaultName: ${{ variables.keyVaultName }}
          virtualNetworkName: ${{ variables.virtualNetworkName }}
          subnetName: ${{ variables.subnetName }}
          registry: ${{ variables.registry }}
          logAnalyticsName: ${{ variables.logAnalyticsName }}
          diagnosticSettingName: ${{ variables.diagnosticSettingName }}
