---
trigger:
  - none

parameters:
  # Resource
  - name: location
    type: string
    default: "westeurope"
  # Postgres
  - name: postgresAdministratorLogin
    type: string
    default: "ckanpostgresadmin"
  - name: postgresCkanLogin
    type: string
    default: "ckan_default"
  - name: postgresCkanDatabaseName
    type: string
    default: "ckan_default"
  - name: postgresSkuTier
    type: string
    default: "GeneralPurpose"
  - name: postgresSkuFamily
    type: string
    default: "Gen5"
  - name: postgresSkuName
    type: string
    default: "GP_Gen5_4"
  - name: postgresGeoRedundantBackup
    type: string
    default: "Disabled"
  - name: postgresStorageAutoGrow
    type: string
    default: "Enabled"
  - name: postgresInfrastructureEncryption
    type: string
    default: "Disabled"
  - name: postgresSslEnforcement
    type: string
    default: "Enabled"
  - name: postgresVersion
    type: string
    default: "11"
  - name: postgresCapacity
    displayName: "vCores allocated for PostgreSQL server"
    type: number
    default: 4
  - name: postgresSizeMB
    displayName: "Starting storage allocated for database"
    type: number
    default: 5120
  - name: postgresBackupRetentionDays
    displayName: "Backup retention days"
    type: number
    default: 7
  # SOLR
  - name: solrCoreName
    displayName: "SOLR core name"
    type: string
    default: "ckan"
  - name: solrSkuName
    displayName: "SOLR App Service Plan SKU Size"
    type: string
    default: "B2"
  - name: solrVersion
    displayName: "SOLR version"
    type: string
    default: "6.5.1"
  - name: solrPasswordKeyName
    displayName: "SOLR Password key name in KeyVault"
    type: string
    default: "SOLRPASSWORD"
  # CKAN
  - name: ckanImageName
    displayName: "CKAN prebuilt docker image name"
    type: string
    default: srhddeuwacr.azurecr.io/ckan:4514

stages:
  - stage: Development
    variables:
      - template: ./templates/variables/dev.yml
      - name: solr_url
        value: "https://${{ variables.solrAppName }}.azurewebsites.net/solr/${{ parameters.solrCoreName }}/"
    jobs:
      - template: ./templates/jobs/ckan-alljobs.yml
        parameters:
          environment: CKANDEV
          location: ${{ parameters.location }}
          postgresAdministratorLogin: ${{ parameters.postgresAdministratorLogin }}
          postgresCkanLogin: ${{ parameters.postgresCkanLogin }}
          postgresCkanDatabaseName: ${{ parameters.postgresCkanDatabaseName }}
          postgresSkuTier: ${{ parameters.postgresSkuTier }}
          postgresSkuFamily: ${{ parameters.postgresSkuFamily }}
          postgresSkuName: ${{ parameters.postgresSkuName }}
          postgresGeoRedundantBackup: ${{ parameters.postgresGeoRedundantBackup }}
          postgresStorageAutoGrow: ${{ parameters.postgresStorageAutoGrow }}
          postgresInfrastructureEncryption: ${{ parameters.postgresInfrastructureEncryption }}
          postgresSslEnforcement: ${{ parameters.postgresSslEnforcement }}
          postgresVersion: ${{ parameters.postgresVersion }}
          postgresCapacity: ${{ parameters.postgresCapacity }}
          postgresSizeMB: ${{ parameters.postgresSizeMB }}
          postgresBackupRetentionDays: ${{ parameters.postgresBackupRetentionDays }}
          solrVersion: ${{ parameters.solrVersion }}
          solrSkuName: ${{ parameters.solrSkuName }}
          solrCoreName: ${{ parameters.solrCoreName }}
          ckan_image: ${{ parameters.ckanImageName }}
          postgresHostName: ${{ variables.postgresHostName }}
          resourceGroup: ${{ variables.resourceGroup }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          keyVaultName: ${{ variables.keyVaultName }}
          virtualNetworkName: ${{ variables.virtualNetworkName }}
          subnetName: ${{ variables.subnetName }}
          solrAppName: ${{ variables.solrAppName }}
          frontendname: ${{ variables.frontendname }}
          solr_url: ${{ variables.solr_url }}
          registry: ${{ variables.registry }}
          appInsightsName: ${{ variables.appInsightsName }}
          logAnalyticsName: ${{ variables.logAnalyticsName }}
          diagnosticSettingName: ${{ variables.diagnosticSettingName }}
          publicStorageAccountName: ${{ variables.publicStorageAccountName }}
  - stage: Test
    variables:
      - template: ./templates/variables/test.yml
      - name: solr_url
        value: "https://${{ variables.solrAppName }}.azurewebsites.net/solr/${{ parameters.solrCoreName }}/"
    jobs:
      - template: ./templates/jobs/ckan-alljobs.yml
        parameters:
          environment: CKANTEST
          location: ${{ parameters.location }}
          postgresAdministratorLogin: ${{ parameters.postgresAdministratorLogin }}
          postgresCkanLogin: ${{ parameters.postgresCkanLogin }}
          postgresCkanDatabaseName: ${{ parameters.postgresCkanDatabaseName }}
          postgresSkuTier: ${{ parameters.postgresSkuTier }}
          postgresSkuFamily: ${{ parameters.postgresSkuFamily }}
          postgresSkuName: ${{ parameters.postgresSkuName }}
          postgresGeoRedundantBackup: ${{ parameters.postgresGeoRedundantBackup }}
          postgresStorageAutoGrow: ${{ parameters.postgresStorageAutoGrow }}
          postgresInfrastructureEncryption: ${{ parameters.postgresInfrastructureEncryption }}
          postgresSslEnforcement: ${{ parameters.postgresSslEnforcement }}
          postgresVersion: ${{ parameters.postgresVersion }}
          postgresCapacity: ${{ parameters.postgresCapacity }}
          postgresSizeMB: ${{ parameters.postgresSizeMB }}
          postgresBackupRetentionDays: ${{ parameters.postgresBackupRetentionDays }}
          solrVersion: ${{ parameters.solrVersion }}
          solrSkuName: ${{ parameters.solrSkuName }}
          solrCoreName: ${{ parameters.solrCoreName }}
          ckan_image: ${{ parameters.ckanImageName }}
          postgresHostName: ${{ variables.postgresHostName }}
          resourceGroup: ${{ variables.resourceGroup }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          keyVaultName: ${{ variables.keyVaultName }}
          virtualNetworkName: ${{ variables.virtualNetworkName }}
          subnetName: ${{ variables.subnetName }}
          solrAppName: ${{ variables.solrAppName }}
          frontendname: ${{ variables.frontendname }}
          solr_url: ${{ variables.solr_url }}
          registry: ${{ variables.registry }}
          appInsightsName: ${{ variables.appInsightsName }}
          logAnalyticsName: ${{ variables.logAnalyticsName }}
          diagnosticSettingName: ${{ variables.diagnosticSettingName }}
          publicStorageAccountName: ${{ variables.publicStorageAccountName }}
