---
trigger:
  - none

stages:
  - stage: Development
    variables:
      - template: ./templates/variables/dev.yml
      - name: solr_url
        value: "https://${{ variables.solrAppName }}.azurewebsites.net/solr/${{ variables.solrCoreName }}/"
    jobs:
      - template: ./templates/jobs/ckan-alljobs.yml
        parameters:
          environment: CKANDEV
          location: ${{ variables.location }}
          postgresAdministratorLogin: ${{ variables.postgresAdministratorLogin }}
          postgresCkanLogin: ${{ variables.postgresCkanLogin }}
          postgresCkanDatabaseName: ${{ variables.postgresCkanDatabaseName }}
          postgresSkuTier: ${{ variables.postgresSkuTier }}
          postgresSkuFamily: ${{ variables.postgresSkuFamily }}
          postgresSkuName: ${{ variables.postgresSkuName }}
          postgresGeoRedundantBackup: ${{ variables.postgresGeoRedundantBackup }}
          postgresStorageAutoGrow: ${{ variables.postgresStorageAutoGrow }}
          postgresInfrastructureEncryption: ${{ variables.postgresInfrastructureEncryption }}
          postgresSslEnforcement: ${{ variables.postgresSslEnforcement }}
          postgresVersion: ${{ variables.postgresVersion }}
          postgresCapacity: ${{ variables.postgresCapacity }}
          postgresSizeMB: ${{ variables.postgresSizeMB }}
          postgresBackupRetentionDays: ${{ variables.postgresBackupRetentionDays }}
          solrVersion: ${{ variables.solrVersion }}
          solrSkuName: ${{ variables.solrSkuName }}
          solrCoreName: ${{ variables.solrCoreName }}
          ckan_image: "${{ variables.registry }}.azurecr.io/ckan:${{ variables.ckanImageTagNumber }}"
          postgresHostName: ${{ variables.postgresHostName }}
          resourceGroup: ${{ variables.resourceGroup }}
          azureResourceManagerConnection: ${{ variables.azureResourceManagerConnection }}
          keyVaultName: ${{ variables.keyVaultName }}
          virtualNetworkName: ${{ variables.virtualNetworkName }}
          subnetName: ${{ variables.subnetNames }}
          solrAppName: ${{ variables.solrAppName }}
          frontendname: ${{ variables.frontendname }}
          solr_url: ${{ variables.solr_url }}
          registry: ${{ variables.registry }}
          appInsightsName: ${{ variables.appInsightsName }}
          logAnalyticsName: ${{ variables.logAnalyticsName }}
          diagnosticSettingName: ${{ variables.diagnosticSettingName }}
          publicStorageAccountName: ${{ variables.publicStorageAccountName }}
