---
trigger:
  - none

parameters:
  - name: resourceGroup
    displayName: "Set the deployment environment"
    type: string
    default: SRHD-D-EUW-RG01
    values:
      - SRHD-D-EUW-RG01
      - SRHD-S-EUW-RG01
      - SRHD-T-EUW-RG01
      - SRHD-P-EUW-RG01

variables:
  - name: location
    value: 'westeurope'
  - name: azureResourceManagerConnection
    value: SC-${{ parameters.resourceGroup }}

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureResourceManagerConnection)
      scriptType: 'pscore'
      scriptLocation: 'scriptPath'
      ScriptPath: './scripts/environment/New-EnvironmentVariables.ps1'
    displayName: Set Azure Subscription ID to task variables
