---
trigger:
  - none

parameters:
  - name: azureResourceManagerConnection
    displayName: "Set the deployment environment"
    type: string

  - name: ckanURL
    displayName: "Enter the URL for the CKAN instance"
    type: string

  - name: names
    displayName: "Enter names (can add multiple names with comma separation)"
    type: string

  - name: emails
    displayName: "Enter emails (must match the number of names)"
    type: string

  - name: apiToken
    displayName: "API Token name in Key Vault"
    type: string
    default: CKANSYSADMINAPITOKEN

variables:
  - template: ./templates/variables/dev.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    inputs:
      filePath: './scripts/agent/Set-AgentTools.ps1'
      pwsh: true
    displayName: Setup Agent Tools

  - task: AzureCLI@2
    inputs:
      azureSubscription: SC-${{ parameters.azureResourceManagerConnection }}
      scriptType: 'pscore'
      scriptLocation: 'scriptPath'
      scriptPath: './scripts/environment/New-EnvironmentVariables.ps1'
      addSpnToEnvironment: true
    displayName: Set Azure Subscription ID to task variables

  - task: AzureCLI@2
    inputs:
      azureSubscription: SC-${{ parameters.azureResourceManagerConnection }}
      scriptType: 'pscore'
      scriptLocation: 'scriptPath'
      scriptPath: './scripts/environment/New-CkanOrgAndUser.ps1'
    env:
      KEYVAULT: $(keyVaultName)
      CKANURL: ${{ parameters.ckanURL }}
      NAMES: ${{ parameters.names }}
      EMAILS: ${{ parameters.emails }}
      APITOKENNAME: ${{ parameters.apiToken }}
    displayName: Create and permission Tech Unit CKAN users and set API tokens
