---
version: "3"

volumes:
  ckan_config: ""
  ckan_home: ""
  ckan_storage: ""

services:
  ckan:
    container_name: ckan
    image: <<IMAGE_NAME_HERE>>
    links:
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:80"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan_default@whockandb:<<PASSWORD_HERE>>@whockandb.postgres.database.azure.com/ckan_default
      - CKAN_SOLR_URL=https://solr-azureappservice235d.azurewebsites.net/solr/ckan/
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_SITE_URL=https://blah.blah
      - POSTGRES_PASSWORD=<<PASSWORD_HERE>>
      - CKAN_POSTGRES_USER=ckan_default
      - CKAN_POSTGRES_HOST=whockandb.postgres.database.azure.com
      - CKAN_DATAPUSHER_URL=http://datapusher:8800

    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"

  redis:
    container_name: redis
    image: redis:latest
